// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Account>;

export function GetContacts(arg1:string):Promise<Array<models.Contact>>;

export function GetEmails(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<models.Email>>;

export function GetEmailsByContact(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<models.Email>>;

export function GetFolders(arg1:string):Promise<Array<models.Folder>>;

export function ListAccounts():Promise<Array<models.Account>>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SearchContacts(arg1:string,arg2:string):Promise<Array<models.Contact>>;

export function Shutdown():Promise<void>;

export function SyncEmails(arg1:string,arg2:string):Promise<void>;

export function SyncFolders(arg1:string):Promise<void>;
