// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddAccount'](arg1, arg2, arg3, arg4);
}

export function GetContacts(arg1) {
  return window['go']['app']['App']['GetContacts'](arg1);
}

export function GetEmails(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetEmails'](arg1, arg2, arg3, arg4);
}

export function GetEmailsByContact(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetEmailsByContact'](arg1, arg2, arg3, arg4);
}

export function GetFolders(arg1) {
  return window['go']['app']['App']['GetFolders'](arg1);
}

export function ListAccounts() {
  return window['go']['app']['App']['ListAccounts']();
}

export function RemoveAccount(arg1) {
  return window['go']['app']['App']['RemoveAccount'](arg1);
}

export function SearchContacts(arg1, arg2) {
  return window['go']['app']['App']['SearchContacts'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['app']['App']['Shutdown']();
}

export function SyncEmails(arg1, arg2) {
  return window['go']['app']['App']['SyncEmails'](arg1, arg2);
}

export function SyncFolders(arg1) {
  return window['go']['app']['App']['SyncFolders'](arg1);
}
